### ISSUE TITLE
Bedrock Reloaded

### ISSUE THREAD

**Issue by U5KUN** [seriousfreezing/SolarApocalypse#2]
Can you add [ViaBedrock](https://github.com/RaphiMC/ViaBedrock) in[ Bedrock Reloaded](https://modrinth.com/modpack/bedrock-reloaded)?

**Comment by seriousfreezing** [comment]
As I understand it, it is a plugin?

**Comment by seriousfreezing** [comment]
If it is just a plugin, I don't think I can put it in because it should be put in servers and not modpacks. But I saw that there is a mod version called ViaFabricPlus (Which allows you to play with the Bedrock version).
