### ISSUE TITLE
Unable to create a new world with the latest version on 1.16.5

### ISSUE THREAD

**Issue by Ozzni** [seriousfreezing/SolarApocalypse#4]
Using version 3.0, for Minecraft version 1.16.5, the game and menus work just fine, but when I attempt to create a world with the mods active, it freezes up on the "Saving world" screen, and make no progress, after completing every other step of world generation successfully.

**Comment by Ozzni** [comment]
Apologies, after further checks it appears that the issue is NOT caused by the modpack, but instead seems to be an issue with the Fabric API for 1.16.5

**Comment by seriousfreezing** [comment]
Ok!
