### ISSUE TITLE
[Bug - 3.9 at 1.20.1 and 1.19.2] opening the Questbook and the game is crashing 

### ISSUE THREAD

**Issue by Bliro** [seriousfreezing/SolarApocalypse#5]
**Describe the bug**
I created the world and try to have a look into the Questbook and the game isn't reacting anymore until i restart the game.

**To Reproduce**
1. Install the game
2. enter a new standard world
3. open inventory
4. hit the Questbook with the mouse

**Crucial information (please complete the following information):**
 - OS: Windows 11 
- Java is version 17.0.8

**Comment by seriousfreezing** [comment]
I'll try to reproduce this bug, but please send me your crashlog or lastest.log

**Comment by seriousfreezing** [comment]
Ok ok, I've just reproduced this bug and it will be fixed in the next version.
